import xml.etree.ElementTree as ET
from functools import cache
from semantic_version import Version
import re


@cache
def get_parsed_file(file_path: str):
    tree = ET.parse(file_path)
    return tree.getroot()


def to_semver(version: str) -> str:
    """
    Converts the nuitka version to a semantic version format for comparison.
    """
    match = re.match(
        r'^(\d+)\.(\d+)(?:\.(\d+))?([a-z]+)(\d+)?$', version, re.IGNORECASE)
    if not match:
        raise ValueError(f"Unrecognized version format: {version}")

    major, minor, patch, label, num = match.groups()
    patch = patch or "0"
    pre = f"-{label}.{num}" if label and num else (
        f"-{label}" if label else "")
    return f"{major}.{minor}.{patch}{pre}"


def get_nuitka_version(file_path: str):
    """
    Returns the Nuitka version used for the build.
    """
    root = get_parsed_file(file_path)

    vers_string = root.get("nuitka_version", "unknown")

    try:
        return Version(vers_string)
    except ValueError:
        return Version(to_semver(vers_string))


def has_nuitka_version_upgraded_report(nuitaka_version: Version):
    """
    Returns True if the report is generated by Nuitka version >= 4.1.0-rc.7, which includes the new object file size information. Otherwise, returns False.
    """
    return nuitaka_version >= Version("4.1.0-rc.7")


def get_plugin_options(file_path: str):
    """
    Returns a list of tuples containing plugin names and their user-enabled status.
    """
    root = get_parsed_file(file_path)

    to_return: list[tuple[str, str]] = []

    # Iterate over modules and sum optimization times
    for plugins in root.findall("plugins"):
        for plugin in plugins.findall("plugin"):
            to_return.append((
                plugin.get("name", "unknown"),
                plugin.get("user_enabled", "unknown")
            ))

    return to_return


def get_command_line(file_path: str):
    """
    Returns a list of command line options used on Nuitka.
    """
    root = get_parsed_file(file_path)

    to_return: list[str] = []

    # Iterate over modules and sum optimization times
    for plugins in root.findall("command_line"):
        for plugin in plugins.findall("option"):
            to_return.append(plugin.get("value", "unknown"))

    return to_return


def get_distributions(file_path: str) -> list[tuple[str, str, str]]:
    """
    Returns a list of tuples (name, version, installer) for each distribution
    listed in the compilation report.
    """
    root = get_parsed_file(file_path)

    to_return: list[tuple[str, str, str]] = []

    for distributions in root.findall("distributions"):
        for dist in distributions.findall("distribution"):
            to_return.append((
                dist.get("name", "unknown"),
                dist.get("version", "unknown"),
                dist.get("installer", "unknown"),
            ))

    return to_return


def get_included(file_path: str, element_name: str) -> list[tuple[str, str, str, str, str, str]]:
    """
    Returns a list of tuples (name, source_path, dest_path, package, ignored, reason) for each
    included element in the compilation report.
    """
    root = get_parsed_file(file_path)
    return [
        (
            ext.get("name", "unknown"),
            ext.get("source_path", "unknown"),
            ext.get("dest_path", "unknown"),
            ext.get("package", ""),
            ext.get("ignored", "unknown"),
            ext.get("reason", "unknown"),
        )
        for ext in root.findall(element_name)
    ]


def get_data_files(file_path: str) -> list[tuple[str, str, int, str, str]]:
    """
    Returns a list of tuples (name, source, size, reason, tags) for each
    data_file in the compilation report.
    """
    root = get_parsed_file(file_path)
    return [
        (
            df.get("name", "unknown"),
            df.get("source", "unknown"),
            int(df.get("size", 0)),
            df.get("reason", "unknown"),
            df.get("tags", ""),
        )
        for df in root.findall("data_file")
    ]


def get_module_metadata(file_path: str) -> dict[str, dict[str, str]]:
    """
    Returns a dict mapping module name to its metadata (kind, usage, reason, source_path)
    extracted from the compilation report XML.
    """
    root = get_parsed_file(file_path)
    metadata: dict[str, dict[str, str]] = {}

    for module in root.findall("module"):
        name = module.get("name", "Unknown")
        meta: dict[str, str] = {}
        for attr in ("kind", "usage", "reason", "source_path"):
            val = module.get(attr)
            if val:
                meta[attr] = val
        if meta:
            metadata[name] = meta

    return metadata


def get_module_stats(file_path: str) -> tuple[int, int]:
    """
    Returns a tuple of the total number of root modules, and a total number of files (including root modules).
    """
    root = get_parsed_file(file_path)

    modules = root.findall("module")
    root_modules = set()
    filenames = set()

    for module in modules:
        name = module.get("name", "Unknown")
        root_module = name.split(".")[0]
        root_modules.add(root_module)
        if "." in name:
            filenames.add(name)

    return len(root_modules), len(filenames)
