import xml.etree.ElementTree as ET
from functools import cache
from semantic_version import Version
import re


@cache
def get_parsed_file(file_path: str):
    tree = ET.parse(file_path)
    return tree.getroot()


def to_semver(version: str) -> str:
    """
    Converts the nuitka version to a semantic version format for comparison.
    """
    match = re.match(
        r'^(\d+)\.(\d+)(?:\.(\d+))?([a-z]+)(\d+)?$', version, re.IGNORECASE)
    if not match:
        raise ValueError(f"Unrecognized version format: {version}")

    major, minor, patch, label, num = match.groups()
    patch = patch or "0"
    pre = f"-{label}.{num}" if label and num else (
        f"-{label}" if label else "")
    return f"{major}.{minor}.{patch}{pre}"


def get_nuitka_version(file_path: str):
    """
    Returns the Nuitka version used for the build.
    """
    root = get_parsed_file(file_path)

    vers_string = root.get("nuitka_version", "unknown")

    try:
        return Version(vers_string)
    except ValueError:
        return Version(to_semver(vers_string))


def has_nuitka_version_upgraded_report(nuitaka_version: Version):
    """
    Returns True if the report is generated by Nuitka version >= 4.1.0-rc.7, which includes the new object file size information. Otherwise, returns False.
    """
    return nuitaka_version >= Version("4.1.0-rc.7")


def get_plugin_options(file_path: str):
    """
    Returns a list of tuples containing plugin names and their user-enabled status.
    """
    root = get_parsed_file(file_path)

    to_return: list[tuple[str, str]] = []

    # Iterate over modules and sum optimization times
    for plugins in root.findall("plugins"):
        for plugin in plugins.findall("plugin"):
            to_return.append((
                plugin.get("name", "unknown"),
                plugin.get("user_enabled", "unknown")
            ))

    return to_return


def get_command_line(file_path: str):
    """
    Returns a list of command line options used on Nuitka.
    """
    root = get_parsed_file(file_path)

    to_return: list[str] = []

    # Iterate over modules and sum optimization times
    for plugins in root.findall("command_line"):
        for plugin in plugins.findall("option"):
            to_return.append(plugin.get("value", "unknown"))

    return to_return
